### ISSUE TITLE
Authentication is not portable to other envs. (say Linux)

### ISSUE THREAD

**Issue by YuilTripathee** [TeeThanakit/mariana-hotel#1]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our slack channel. Please use [stackoverflow](https://stackoverflow.com) for supporting issues.

Mr. Tee can login using authentication function that he had built on front-end.

## Expected Behavior

Authentication should work as in his local environment.

## Current Behavior

No login logout feature.

## Possible Solution

- Add auth with JWT and RBAC. (possibly)

## Steps to Reproduce

1. Clone the test branch.
2. `cd frontend && npm install`
3. `npm run dev`
4. Go to: `http://localhost:3000`, navigate to login interface and hit login/logout.

**Comment by TeeThanakit** [comment]
fixed, spent couple hrs to fix this gg

**Comment by TeeThanakit** [comment]
fixed, spent couple hrs to fix this gg

**Comment by TeeThanakit** [comment]
fixed, gg
